version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Keep the stdin open to support attaching to app containers process for binding.pry
    tty: true
    # Allow for sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
    stdin_open: true
    command: bash -c "rm -rf /app/tmp/pids/server.pid && bundle install && bundle exec rdbg -n --open --host 0.0.0.0 --port 12345 -c -- bin/rails server -p 3000 -b 0.0.0.0"
    # command: sleep infinity
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "12345:12345"
    environment:
      RAILS_ENV: development
      VITE_RUBY_HOST: vite
    depends_on:
      - db

  vite:
    container_name: vite
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: bash -c "bundle install && npm install && bin/vite dev"
    ports:
      - "3036:3036"
    volumes:
      - .:/app
    environment:
      DEBUG: '*vite*'
      RAILS_ENV: development
      VITE_RUBY_HOST: 0.0.0.0
    depends_on:
      - app

  db:
    container_name: db
    image: postgres:16.3-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .devcontainer/create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql

  adminer:
    container_name: adminer
    image: "adminer:latest"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
