version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      RAILS_ENV: development
      # TODO: https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
      VITE_CJS_IGNORE_WARNING: true
      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgresSQL locally.
  db:
    image: postgres:16.3-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password

  adminer:
    image: "adminer:latest"
    restart: always
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    depends_on:
      - db

volumes:
  postgres-data:
